cask_args appdir: "/Applications"

tap "sanemat/font"
tap "homebrew/cask"
tap "bagonyi/homebrew-formulae"

brew "anyenv"
brew "fish"
brew "git"
brew "git-secrets"
brew "jq"
brew "tree"
brew "watch"
brew "wget"
brew "ricty", args: ["with-powerline"]
brew "mecab"
brew "mecab-ipadic"
brew "leveldb@1.22"

cask "google-cloud-sdk"
cask "appcleaner"
cask "aws-vault"
cask "docker"
cask "google-chrome"
cask "notion"
cask "rectangle"
cask "slack"
cask "visual-studio-code"
cask "zoom"
